config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :gossips
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to:'pages#home'
  get '/team', to:'pages#team'
  get '/contact', to:'pages#contact'
  get '/welcome/:name', to: 'pages#welcome'
  resources :gossips

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user,:dependent => :destroy

end

app/models/user.rb
class User < ApplicationRecord
    has_many :gossips, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :set_gossip, only: %i[ show edit update destroy ]

  # GET /gossips or /gossips.json
  def index
    @gossips = Gossip.all
  end

  # GET /gossips/1 or /gossips/1.json
  def show
    
  end

  # GET /gossips/new
  def new
    @gossip = Gossip.new
  end

  # GET /gossips/1/edit
  def edit
  end

  # POST /gossips or /gossips.json
  def create
    @gossip = Gossip.create(title: params[:gossip][:title], content: params[:gossip][:content], user_id: 2)
    redirect_to gossips_url
  end

  # PATCH/PUT /gossips/1 or /gossips/1.json
  def update
    respond_to do |format|
      if @gossip.update(gossip_params)
        format.html { redirect_to @gossip, notice: "Gossip was successfully updated." }
        format.json { render :show, status: :ok, location: @gossip }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gossip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gossips/1 or /gossips/1.json
  def destroy
    @gossip.destroy
    respond_to do |format|
      format.html { redirect_to gossips_url, notice: "Gossip was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gossip
      @gossip = Gossip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gossip_params
      params.require(:gossip).permit(:title, :content)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @gossips = Gossip.all
    end
    def team
        
    end
    def contact
        
    end
    def welcome
        @name = params['name']
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gossips/_form.html.erb
<%= form_with(model: gossip) do |form| %>
  <% if gossip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gossip.errors.count, "error") %> prohibited this gossip from being saved:</h2>

      <ul>
        <% gossip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gossips/edit.html.erb
<h1>Editing Gossip</h1>

<%= link_to 'Show', @gossip %> |
<%= link_to 'Back', gossips_path %>

<%= form_for(@gossip) do |f| %>

  <div class="field">
    <%= f.label :titre %><br>
    <%= f.text_field :title %><br>
    <%= f.label :contenu %><br>
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gossips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liste des pottins</h1>

<table>
  <thead>
    <tr>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
  <%= link_to 'New Gossip', new_gossip_path %>

    <% @gossips.each do |gossip| %>
      <tr>
        <td><%= gossip.id %></td>
        <td><%= gossip.title %></td>
        <td><%= link_to 'Voir', gossip, {:class=>"btn btn-primary" } %></td>
        <td><%#= link_to 'Edit', edit_gossip_path(gossip) , {:class=>"btn btn-primary" } %></td>
        <td><%#= link_to 'Destroy', gossip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/gossips/new.html.erb
<h1>Nouveau pottin</h1>

<%=form_with model: @gossip, url: gossips_path do |f| %>
    <div class="form-group">
    <label>Titre de l'article</label>
    <%= f.text_field :title %>
    </div>
    <div class="form-group">
    <label>Contenu de l'article</label>
    <%= f.text_field :content %>
    </div>
    <button type="submit">Créer</button>
<% end %>

app/views/gossips/show.html.erb
<p id="notice"><%= notice %></p>

<%#= link_to 'Edit', edit_gossip_path(@gossip) %> |
<%= link_to 'Back', gossips_path %>

<h2><%=@gossip.id%> - <%=@gossip.title%></h2>
<p><%=@gossip.content%></p>
<h6>Potin creer par  <%= link_to @gossip.user.first_name , user_path(@gossip.user) %> </h6>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Gossip",  root_path ,{:class=>"navbar-brand",:id=>"link_home" } %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <%= link_to "contact",  contact_path ,{:class=>"nav-link" } %>
            </li>
            <li class="nav-item">
                <%= link_to "team",  team_path ,{:class=>"nav-link" }%>
            </li>
                        <li class="nav-item">
                <%= link_to "gossips",  gossips_path ,{:class=>"nav-link" }%>
            </li>
                        <li class="nav-item">
                <%= link_to "users",  users_path ,{:class=>"nav-link" }%>
            </li>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

    <%= render 'layouts/navbar' %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/contact.html.erb
<h1 class="contact_title">Nous contacter</h1>

<div class="contact">
<p>étape 1 : acheter un pigeon</p>
<p>étape 2 : le dresser</p>
<p>étape 3 : nous l'envoyer <a target="_blank" href="https://www.google.fr/maps/place/Dev+City+Rd,+Shayona+City,+Chanakyapuri,+Ahmedabad,+Gujarat+380081,+Inde/@23.0828649,72.5352277,17z/data=!3m1!4b1!4m5!3m4!1s0x395e8338bb2cd699:0xf611cb7193d3575d!8m2!3d23.08286!4d72.5374164">ici</a></p>
</div>

app/views/pages/home.html.erb
<%@gossips.each do |gossip| %>
    <div class="full_gossip">
        <h4 class="title_gossip"><%=gossip.user.first_name%><h4>
        <p class="content_gossip"><%=gossip.content %></p>
    </div>
<% end %>

app/views/pages/team.html.erb
<div class="team mt-2">
    <div class="card m-1" style="max-width: 200px !important;">
        <img style="max-width: 200px;" src="https://avatars.githubusercontent.com/u/23138145?v=4" alt="img presentation">
        <h2>Jocelin</h2>
    </div>
    <div class="card m-1" style="max-width: 200px !important;">
        <img style="max-width: 200px;" src="https://avatars.githubusercontent.com/u/74005033?v=4" alt="img presentation">
        <h2>Leo</h2>
    </div>
</div>

app/views/pages/welcome.html.erb
<p id="hidden_url">BIENVENUE <%= @name%> ! Ici c'est notre super site de potins, il est chouette, non ?</p>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liste des auteurs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Voir', user, {:class=>"btn btn-primary" }%></td>
        <td><%#= link_to 'Edit', edit_user_path(user) %></td>
        <td><%#= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<% link_to 'Back', users_path %>
<h5>
<%= @user.id %>
<%= @user.first_name %>
<%= @user.last_name %>
</h5>
<h6> <%= @user.description %> </h6>

<br>

<% @user.gossips.each do |gossip| %>

<h6> <%= link_to gossip.title , gossip_path %></h6>
<p> <%=  gossip.content %>  </p>
<% end %>

<br>
<%# link_to 'Edit', edit_user_path(@user) %> 